### ISSUE TITLE
Convert MDP (FireAlpaca) files to OCI (openCanvas 2.0+) files

### ISSUE THREAD

**Issue by DemiWrath** [weeb-poly/krita-plugin-mdp#1]
I was wondering if you know of a way to open fireAlpaca files in open canvas 7?

**Comment by tcyrus** [comment]
I'm sorry if the README wasnt clear, but we aren't affiliated with FireAlpaca or openCanvas. I made this project so that I could open simple mdp files in Krita (which kinda works). I was under the impression that openCanvas supported mdp files, but I guess I was wrong. I'll update the README to clear this up.

This isn't really an issue with our project, so I'm going to close the issue once I update the README.

I don't have a license for openCanvas so I don't think I'm going to be much help, but I would suggest using FireAlpaca to export a PSD file and trying to open that in openCanvas.

**Comment by DemiWrath** [comment]
Thanks anyway, sorry to bother. Btw I'm actually using the 120 day free trial for openCanvas! (the only issue is I have a shit ton of mdp files from using FireAlpaca for more than a year... time to scout for another fix somewhere!)

**Comment by tcyrus** [comment]
Sorry that I couldn't be of much help. FireAlpaca doesn't appear to have a command line export mode like Krita does. You might be able to do something with [AutoHotkey](https://www.autohotkey.com/), but that's something you'd have to figure out on your own. I tried making something

This Krita plugin is unable to link into Krita's actual file import/export functionality (`impex`) due to the limitations of the PyKrita API, so there's no way that this could help with bulk conversion (also, this plugin doesn't always work, so you're better off with the actual application for the most part).

I'm going to try and update the plugin so that it can open multiple MDP files at once, but I don't know if that will actually help.

I made a post on [/r/firealpaca](https://www.reddit.com/r/firealpaca/) ([link](https://redd.it/ygowla)), but I'd recommend submitting a [Proposal / Bug Report](https://firealpaca.com/report/) if this is a feature that you want.

**Comment by tcyrus** [comment]
Updated the issue title to reflect the original question asked.
Again, sorry about the confusion. References to openCanvas have been removed from the README to prevent this from happening again.
The OCI (openCanvas 2.0+) and WPB (openCanvas 1.1) file formats are undocumented as far as I know, which makes it hard to create an `impex` plugin for it.

Using the FireAlpaca app to do the conversion is generally the best option, as there's a chunk of the MDP file format that we're unable to handle either due to limitations of Krita or lack of documentation on FireAlpaca.
I really hope that FireAlpaca adds a headless export mode for converting files in batch, because that would be really helpful for asset pipelines.

I made a short script to assist with converting MDP files to PSD using keyboard automation ([link](https://gist.github.com/5fc4323daf44e263fbc52d494c48a82d)). It isn't great by any means, but it's better than nothing.
